# deploy app to the production server
name: Deploy

on:
  release:
    types: [created]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # deploy to the server using SSH
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22

        # script to run on the server
        script: |
          # cloning the repository if it is not found
          if [ ! -d "/services/website/code-paste" ]; then
            sudo mkdir -p /services/website && \
            sudo git clone https://github.com/lordbecvold/code-paste /services/website/code-paste
          fi

          # go to the project directory
          if [ -d "/services/website/code-paste" ]; then
            cd /services/website/code-paste
          else
            echo "Directory /services/website/code-paste not found."
            exit 1
          fi

          # pull the latest changes
          git pull || { echo "Git pull failed"; exit 1; }

          # run the upgrade script if it exists
          if [ -f "scripts/upgrade.sh" ]; then
            sh scripts/upgrade.sh
          else
            echo "Upgrade script not found."
            exit 1
          fi
