# run statuc analysis with PHPStan
name: PHPStan

on:
  push:
    branches:
      - main

jobs:
  phpstan:
    name: PHPStan analyse
    runs-on: ubuntu-latest

    steps:
    # checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # setup PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2

    # install dependencies
    - name: Install dependencies
      run: composer install

    # run PHPStan analysis
    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyse --configuration phpstan.neon
