# run unit tests with PHPUnit
name: PHPUnit Tests

on:
  push:
    branches:
      - main

jobs:
  phpunit:
    name: Run PHPUnit
    runs-on: ubuntu-latest

    # required services
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    # phpunit tests process
    steps:
      # checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # setup PHP environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl, pdo_mysql, pdo, mysqli, zip

      # install dependencies
      - name: Install dependencies
        run: sh scripts/install.sh
      
      # migrate database
      - name: Migrate database
        run: sh scripts/migrate.sh

      # run PHPUnit tests
      - name: Run PHPUnit tests
        run: php bin/phpunit
